[env]
SHORT_SHA = "{{exec(command='git rev-parse --short HEAD')}}"
PWD = "{{exec(command='pwd')}}"

[tasks.short-sha]
run = "echo $SHORT_SHA"

[tasks.download-sam2]
run = """
cd checkpoints
bash download_ckpts.sh
"""
[tasks.download-grounding-dino]
run = """
cd gdino_checkpoints
bash download_ckpts.sh
"""
[tasks.download-models]
depends = ["download-sam2", "download-grounding-dino"]

[tasks.build]
run = """
docker build --build-arg USE_CUDA="1" \
	--build-arg TORCH_ARCH="7.0;7.5;8.0;8.6+PTX" \
	-t grounded_sam2:latest .
"""

[tasks.run]
run = """
docker run \
--gpus all \
-v $PWD:/home/appuser/Grounded-SAM-2 \
-p 58080:58080 \
grounded_sam2:latest
"""

[tasks.run_local]
run = "gunicorn -c src/gunicorn.conf.py"

[tasks.pull-upstream]
run = """
git remote add upstream
git fetch upstream
git checkout main
git merge upstream/main
"""

[tasks.lint]
run = "ruff check . --fix"
[tasks.format]
run = "ruff format ."
[tasks.vet]
depends = ["lint", "format"]

[tasks.test]
run = "python -m pytest tests"

[tasks.download-stubs]
run = "mypy --install-types --non-interactive"
